import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Provider from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Imdb Clone",
  description: "Generated by Mohammad abuzer khan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider defaultTheme ="system" attribute="class" >
        <Header/>
        {children}
        </Provider>
        </body>
 
    </html>
  );
}
